# coding: utf-8
""" Basic configuration for running tests and generating documentation.

Because Django apps are so tied to Django, it is necessary to configure
Django's settings module before tests can be run or documentation can
be successfully generated by Sphinx.
"""
import os
from django.conf import settings, global_settings

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

if not settings.configured and not os.environ.get('DJANGO_SETTINGS_MODULE'):
  settings.configure(
      DATABASES={
          'default': {
              'ENGINE': 'django.db.backends.sqlite3',
          },
        },
      INSTALLED_APPS=[
          'django.contrib.auth',
          'django.contrib.admin',
          'django.contrib.contenttypes',
          'django.contrib.sessions',
          'djoauth2',
        ],
      TEMPLATE_DIRS=(
          os.path.join(SITE_ROOT, 'djoauth2/tests/templates'),
        ),
      ROOT_URLCONF='djoauth2.tests.test_urls',
      FIXTURE_DIRS=(
          os.path.join(SITE_ROOT, 'djoauth2/tests/fixtures'),
        ),
      DEBUG=False,
    )

